### ISSUE TITLE
MQTT Payload New format?

### ISSUE THREAD

**Issue by bitvijays** [fablabbcn/smartcitizen-kit-21#31]
Dear SCK Team/ @oscgonfer ,

Hope you are doing well. Just wanted to ask .. Has the MQTT payload format has been changed? 

- Previously, the SCK device used to send the data to `device/sck/device_token/readings`  and now it is sending it to `device/sck/device_token/readings/raw`.
- Previously it was a JSON format, however it seems, now things are bit changed? 

Kind Regards,
bitvijays

**Comment by oscgonfer** [comment]
Dear @bitvijays 

Yes, it has recently. It was mainly done to reduce the payload size by removing quotes, sensor names and so on. You can check the discussion in the forum here: https://forum.smartcitizen.me/t/invalid-json-format-in-kits-output-payload/1665

**Comment by bitvijays** [comment]
Thank @oscgonfer for the quick reply. Much appreciated 👍  Have a nice day !
