### ISSUE TITLE
./make.py -h should not give error message 

### ISSUE THREAD

**Issue by uraich** [fablabbcn/smartcitizen-kit-21#43]
when running ./make.py -h you get the error message:
You need to specify at least one action!!!
The check for actions should be moved away from the check for the help function

**Comment by vicobarberan** [comment]
Thanks for reporting, it should be fixed with [2d8e695](https://github.com/fablabbcn/smartcitizen-kit-21/commit/2d8e695c777773f43b67f123b11c309051bcbc71)
