### ISSUE TITLE
OLED Display does not work

### ISSUE THREAD

**Issue by nicpom** [fablabbcn/smartcitizen-kit-21#9]
Grove OLED Display does not work, neither old model nor new one. 

Or documentation should be corrected, or firmware fixed.

![image](https://user-images.githubusercontent.com/31170413/72178382-0ef8ca80-33e3-11ea-9280-8ae025bf0166.png)

**Comment by oscgonfer** [comment]
Hi, 

Which version of the firmware are you using? 
Referenced in the forum for other visitors:
https://forum.smartcitizen.me/t/oled-display-help/1313/4

**Comment by vicobarberan** [comment]
OLED display support is included in [release 0.9.8](https://github.com/fablabbcn/smartcitizen-kit-21/releases), you can check the  documentation [here](https://docs.smartcitizen.me/Guides/deployments/OLED%20display/) and if you still have problems please open a new issue.
